<?php

namespace VirginMedia\ChannelGuideBundle\Entity;

use Doctrine\ORM\EntityRepository;

/**
 * ChannelRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class ChannelRepository extends EntityRepository
{
    public function channelPackage($package_ids)
    {
        $qb = $this->createQueryBuilder('c')
            ->leftJoin('c.packageChannels','p')
            ->where("p.id IN(:ids)")
            ->setParameter('ids', array_values($package_ids))
            ->orderBy('c.id', 'ASC');
        return $qb->getQuery()->execute();
    }

    public function channelRegion($region)
    {
        $qb = $this->createQueryBuilder('c')
            ->leftJoin('c.regionChannels','r')
            ->where("r.id = :id")
            ->setParameter('id', $region)
            ->orderBy('c.id', 'ASC');
        return $qb->getQuery()->execute();
    }
}
